//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yemek_Tarifi_Sitesi_2._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Hakkimizda
    {
        public byte Metinid { get; set; }
        public string Metin { get; set; }
    }
}
