//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yemek_Tarifi_Sitesi_2._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Yemekler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Yemekler()
        {
            this.Tbl_Yorumlar = new HashSet<Tbl_Yorumlar>();
        }
    
        public short Yemekid { get; set; }
        public string YemekAd { get; set; }
        public string YemekMalzeme { get; set; }
        public string YemekTarif { get; set; }
        public string YemekResim { get; set; }
        public Nullable<System.DateTime> YemekTarih { get; set; }
        public Nullable<double> YemekPuan { get; set; }
        public Nullable<short> Kategoriid { get; set; }
        public Nullable<bool> durum { get; set; }
    
        public virtual Tbl_Kategoriler Tbl_Kategoriler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Yorumlar> Tbl_Yorumlar { get; set; }
    }
}
