//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yemek_Tarifi_Sitesi_2._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Mesajlar
    {
        public short Mesajid { get; set; }
        public string MesajGönderen { get; set; }
        public string MesajMail { get; set; }
        public string MesajBaslik { get; set; }
        public string MesajIcerik { get; set; }
    }
}
